---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-data
data:
  sample-data.csv: |
    Jill,Doe
    Joe,Doe
    Justin,Doe
    Jane,Doe
    John,Doe
    Maria,Doe
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-spring-batch
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: sample-data
              configMap:
                name: sample-data
                defaultMode: 420
          restartPolicy: Never
          containers:
            - name: job-spring-batch
              image: image-registry.openshift-image-registry.svc:5000/batch/spring-batch:latest
              volumeMounts:
                - name: sample-data
                  mountPath: /home/jboss/sample-data.csv
                  subPath: sample-data.csv
